/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetointegradorview;

import ProjetoIntegrador.DAO.ClientesDAO;
import java.util.List;
import ProjetoIntegrador.model.Enderecos;
import javax.swing.JFormattedTextField;
import ProjetoIntegrador.DAO.EnderecoDAO;
import ProjetoIntegrador.model.Clientes;
import ProjetoIntegrador.model.Enderecos;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author robert.dettenborn
 */
public class telaClientes extends javax.swing.JFrame {

    /**
     * Creates new form telaClientes
     */
    public telaClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPaneltlcliente = new javax.swing.JPanel();
        jPanelCabCliente = new javax.swing.JPanel();
        jLabeltelacadscliente = new javax.swing.JLabel();
        jTabbedPanecadastrocliente = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabelNomeCliente = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelCPF = new javax.swing.JLabel();
        jComboBoxenderecouf = new javax.swing.JComboBox<>();
        jLabelCEP = new javax.swing.JLabel();
        jLabelendereçocliente = new javax.swing.JLabel();
        jLabelrua = new javax.swing.JLabel();
        jTextFieldruacliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabelbairrocliente = new javax.swing.JLabel();
        jTextFieldbairrocliente = new javax.swing.JTextField();
        jTextFieldnomecliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldcomplemento = new javax.swing.JTextField();
        jComboBoxEnderecoscadastrados = new javax.swing.JComboBox<>();
        jButtonsalvarSalvarEndereco = new javax.swing.JButton();
        jButtonlistarEndereco = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldcidade = new javax.swing.JTextField();
        jFormattedTextFieldcepcliente = new javax.swing.JFormattedTextField();
        jFormattedTextFieldnumero = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCPF = new javax.swing.JFormattedTextField();
        jFormattedTextFieldtelefonecliente = new javax.swing.JFormattedTextField();
        jLabelNomeClienteIdentificador = new javax.swing.JLabel();
        jTextFieldnomeclienteIdentificador = new javax.swing.JTextField();
        jButtonNovoCadastro = new javax.swing.JButton();
        jButtonAtualizar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        jLabelconsultanomecliente = new javax.swing.JLabel();
        jTextFieldpesquisa = new javax.swing.JTextField();
        buttonpesquisar = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelCabCliente.setBackground(new java.awt.Color(102, 204, 0));
        jPanelCabCliente.setToolTipText("CADASTRO CLIENTE");

        jLabeltelacadscliente.setFont(new java.awt.Font("Palatino Linotype", 1, 24)); // NOI18N
        jLabeltelacadscliente.setText("Cadastro de Cliente");

        javax.swing.GroupLayout jPanelCabClienteLayout = new javax.swing.GroupLayout(jPanelCabCliente);
        jPanelCabCliente.setLayout(jPanelCabClienteLayout);
        jPanelCabClienteLayout.setHorizontalGroup(
            jPanelCabClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCabClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabeltelacadscliente, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(514, Short.MAX_VALUE))
        );
        jPanelCabClienteLayout.setVerticalGroup(
            jPanelCabClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCabClienteLayout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addComponent(jLabeltelacadscliente, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabelNomeCliente.setText("NOME:");

        jLabel4.setText("E-MAIL:");

        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });

        jLabelCPF.setText("CPF:");

        jComboBoxenderecouf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO;" }));
        jComboBoxenderecouf.setToolTipText("");
        jComboBoxenderecouf.setActionCommand("");
        jComboBoxenderecouf.setName("UF"); // NOI18N
        jComboBoxenderecouf.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxenderecoufItemStateChanged(evt);
            }
        });
        jComboBoxenderecouf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxenderecoufActionPerformed(evt);
            }
        });

        jLabelCEP.setText("CEP:");

        jLabelendereçocliente.setText("Endereço:");

        jLabelrua.setText("Rua:");

        jTextFieldruacliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldruaclienteActionPerformed(evt);
            }
        });

        jLabel3.setText("Fone:");

        jLabelbairrocliente.setText("Bairro:");

        jTextFieldbairrocliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldbairroclienteActionPerformed(evt);
            }
        });

        jTextFieldnomecliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnomeclienteActionPerformed(evt);
            }
        });

        jLabel1.setText("N° :");

        jLabel2.setText("UF:");

        jLabel5.setText("Comp.:");

        jTextFieldcomplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldcomplementoActionPerformed(evt);
            }
        });

        jComboBoxEnderecoscadastrados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxEnderecoscadastrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEnderecoscadastradosActionPerformed(evt);
            }
        });

        jButtonsalvarSalvarEndereco.setText("SALVAR ENDEREÇO");
        jButtonsalvarSalvarEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsalvarSalvarEnderecoActionPerformed(evt);
            }
        });

        jButtonlistarEndereco.setText("LISTAR ENDEREÇO");
        jButtonlistarEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonlistarEnderecoActionPerformed(evt);
            }
        });

        jLabel6.setText("Cidade:");

        jTextFieldcidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldcidadeActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldcepcliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldcepcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldcepclienteActionPerformed(evt);
            }
        });

        jFormattedTextFieldnumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextFieldnumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldnumeroActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCPFActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldtelefonecliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldtelefonecliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldtelefoneclienteActionPerformed(evt);
            }
        });

        jLabelNomeClienteIdentificador.setText("IDENTIFICADOR:");

        jTextFieldnomeclienteIdentificador.setEnabled(false);
        jTextFieldnomeclienteIdentificador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnomeclienteIdentificadorActionPerformed(evt);
            }
        });

        jButtonNovoCadastro.setText("NOVO CADASTRO");
        jButtonNovoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoCadastroActionPerformed(evt);
            }
        });

        jButtonAtualizar.setText("ATUALIZAR");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("EXCLUIR");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelCEP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldcepcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelbairrocliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldbairrocliente, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldcomplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 133, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jButtonNovoCadastro))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelNomeCliente)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                                    .addComponent(jTextFieldnomecliente))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextFieldtelefonecliente, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabelCPF)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelendereçocliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxEnderecoscadastrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(jButtonsalvarSalvarEndereco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonlistarEndereco))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelNomeClienteIdentificador)
                                .addGap(8, 8, 8)
                                .addComponent(jTextFieldnomeclienteIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelrua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldruacliente, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jTextFieldcidade, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jButtonAtualizar)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jButtonExcluir))
                                    .addComponent(jComboBoxenderecouf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeClienteIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldnomeclienteIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldnomecliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCPF)
                    .addComponent(jFormattedTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldtelefonecliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxEnderecoscadastrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonsalvarSalvarEndereco)
                    .addComponent(jButtonlistarEndereco)
                    .addComponent(jLabelendereçocliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelbairrocliente, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCEP)
                    .addComponent(jTextFieldbairrocliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldcepcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldcomplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelrua)
                    .addComponent(jTextFieldruacliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxenderecouf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovoCadastro)
                    .addComponent(jButtonAtualizar)
                    .addComponent(jButtonExcluir))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jTabbedPanecadastrocliente.addTab("Cadastro Cliente", jPanel2);

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Identificador", "Nome", "Cpf", "Email", "Telefone"
            }
        ));
        jTableClientes.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTableClientesAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableClientes);

        jLabelconsultanomecliente.setText("Nome:");

        jTextFieldpesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldpesquisaActionPerformed(evt);
            }
        });

        buttonpesquisar.setActionCommand("PESQUISA");
        buttonpesquisar.setLabel("Pesquisar");
        buttonpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonpesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelconsultanomecliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(buttonpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelconsultanomecliente)
                        .addComponent(jTextFieldpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jTabbedPanecadastrocliente.addTab("Consulta de Clientes", jPanel3);

        javax.swing.GroupLayout jPaneltlclienteLayout = new javax.swing.GroupLayout(jPaneltlcliente);
        jPaneltlcliente.setLayout(jPaneltlclienteLayout);
        jPaneltlclienteLayout.setHorizontalGroup(
            jPaneltlclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCabCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPaneltlclienteLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jTabbedPanecadastrocliente, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPaneltlclienteLayout.setVerticalGroup(
            jPaneltlclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneltlclienteLayout.createSequentialGroup()
                .addComponent(jPanelCabCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPanecadastrocliente, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneltlcliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPaneltlcliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonpesquisarActionPerformed
        
        if(jTextFieldpesquisa.getText().isBlank()){
           ClientesDAO dao = new ClientesDAO(); 
           List<Clientes> lista = dao.listarClientes();
           DefaultTableModel tabela = (DefaultTableModel)jTableClientes.getModel();
           tabela.setNumRows(0);
           for(Clientes cliente: lista){ 
               tabela.addRow(new Object[]{ 
                   cliente.getId(),
                   cliente.getNome(),
                   cliente.getCpf(),
                   cliente.getEmail(),
                   cliente.getTelefone(),} );
            }
        } else {
            ClientesDAO dao = new ClientesDAO();
            List<Clientes> lista = dao.buscarClientes(jTextFieldpesquisa.getText());
            DefaultTableModel tabela = (DefaultTableModel) jTableClientes.getModel();
            tabela.setNumRows(0);
            for (Clientes cliente : lista) {
                tabela.addRow(new Object[]{
                    cliente.getId(),
                    cliente.getNome(),
                    cliente.getCpf(),
                    cliente.getEmail(),
                    cliente.getTelefone(),});
            }
        }
    }//GEN-LAST:event_buttonpesquisarActionPerformed

    private void jTextFieldpesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldpesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldpesquisaActionPerformed

    private void jTextFieldbairroclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldbairroclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldbairroclienteActionPerformed

    private void jComboBoxenderecoufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxenderecoufActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxenderecoufActionPerformed

    private void jComboBoxenderecoufItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxenderecoufItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxenderecoufItemStateChanged

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldnomeclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnomeclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldnomeclienteActionPerformed

    private void jButtonsalvarSalvarEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsalvarSalvarEnderecoActionPerformed
        try {
            Enderecos endereco = new Enderecos();
            endereco.setCep(jFormattedTextFieldcepcliente.getText());
            endereco.setRua(jTextFieldruacliente.getText());
            endereco.setNumero(Integer.parseInt(jFormattedTextFieldnumero.getText()));
            endereco.setComplemento(jTextFieldcomplemento.getText());
            endereco.setBairro(jLabelbairrocliente.getText());
            endereco.setCidade(jTextFieldcidade.getText());
            endereco.setUF(jComboBoxenderecouf.getSelectedItem().toString());

            EnderecoDAO enderecoDAO = new EnderecoDAO();
            enderecoDAO.cadastrarEnderecos(endereco);
        } catch (NumberFormatException e) {
        }
    }//GEN-LAST:event_jButtonsalvarSalvarEnderecoActionPerformed

    private void jButtonlistarEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonlistarEnderecoActionPerformed
        new FrmListarEnderecos().setVisible(true);
    }//GEN-LAST:event_jButtonlistarEnderecoActionPerformed

    private void jTextFieldnomeclienteIdentificadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnomeclienteIdentificadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldnomeclienteIdentificadorActionPerformed

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        Clientes cliente = new Clientes();
        cliente.setNome(jTextFieldnomecliente.getText());
        cliente.setCpf(jFormattedTextFieldCPF.getText());
        cliente.setEmail(jTextFieldEmail.getText());
        cliente.setTelefone(jFormattedTextFieldtelefonecliente.getText());
        cliente.setId(Integer.parseInt(jTextFieldnomeclienteIdentificador.getText()));

        ClientesDAO dao = new ClientesDAO();
        dao.atualizarCliente(cliente);
    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jFormattedTextFieldCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCPFActionPerformed

    private void jButtonNovoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoCadastroActionPerformed
          
        try {
            Clientes cliente = new Clientes();
            cliente.setNome(jTextFieldnomecliente.getText());
            cliente.setCpf(jFormattedTextFieldCPF.getText());
            cliente.setEmail(jTextFieldEmail.getText());
            cliente.setTelefone(jFormattedTextFieldtelefonecliente.getText());

            ClientesDAO dao = new ClientesDAO();
            dao.cadastrarCliente(cliente);

            if (!jTextFieldruacliente.getText().isBlank()) {

                Enderecos endereco = new Enderecos();
                endereco.setCep(jFormattedTextFieldCPF.getText());
                endereco.setRua(jTextFieldruacliente.getText());
                endereco.setNumero(Integer.parseInt(jFormattedTextFieldnumero.getText()));
                endereco.setComplemento(jTextFieldcomplemento.getText());
                endereco.setBairro(jTextFieldbairrocliente.getText());
                endereco.setCidade(jTextFieldcidade.getText());
                endereco.setUF(jComboBoxenderecouf.getSelectedItem().toString());
                endereco.setCliente(cliente);

                EnderecoDAO daoEnd = new EnderecoDAO();
                daoEnd.cadastrarEnderecos(endereco);

            }
        } catch (NumberFormatException e) {

        }

    }//GEN-LAST:event_jButtonNovoCadastroActionPerformed

    private void jTableClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientesMouseClicked
       jTextFieldnomeclienteIdentificador.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 0).toString());
        jTextFieldnomecliente.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 1).toString());
        jFormattedTextFieldCPF.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 2).toString());
        jTextFieldEmail.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 3).toString());
        jFormattedTextFieldtelefonecliente.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 4).toString());
        
         jTabbedPanecadastrocliente.setSelectedIndex(0);

    }//GEN-LAST:event_jTableClientesMouseClicked

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        Clientes clientes = new Clientes();
        clientes.setId(Integer.parseInt(jTextFieldnomeclienteIdentificador.getText()));
        ClientesDAO dao = new ClientesDAO();
        dao.deletarCliente(clientes);
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTableClientesAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTableClientesAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableClientesAncestorAdded

    private void jFormattedTextFieldtelefoneclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldtelefoneclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldtelefoneclienteActionPerformed

    private void jComboBoxEnderecoscadastradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEnderecoscadastradosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEnderecoscadastradosActionPerformed

    private void jFormattedTextFieldcepclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldcepclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldcepclienteActionPerformed

    private void jFormattedTextFieldnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldnumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldnumeroActionPerformed

    private void jTextFieldcomplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldcomplementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldcomplementoActionPerformed

    private void jTextFieldruaclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldruaclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldruaclienteActionPerformed

    private void jTextFieldcidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldcidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldcidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button buttonpesquisar;
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovoCadastro;
    private javax.swing.JButton jButtonlistarEndereco;
    private javax.swing.JButton jButtonsalvarSalvarEndereco;
    private javax.swing.JComboBox<String> jComboBoxEnderecoscadastrados;
    private javax.swing.JComboBox<String> jComboBoxenderecouf;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF;
    private javax.swing.JFormattedTextField jFormattedTextFieldcepcliente;
    private javax.swing.JFormattedTextField jFormattedTextFieldnumero;
    private javax.swing.JFormattedTextField jFormattedTextFieldtelefonecliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelCEP;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelNomeCliente;
    private javax.swing.JLabel jLabelNomeClienteIdentificador;
    private javax.swing.JLabel jLabelbairrocliente;
    private javax.swing.JLabel jLabelconsultanomecliente;
    private javax.swing.JLabel jLabelendereçocliente;
    private javax.swing.JLabel jLabelrua;
    private javax.swing.JLabel jLabeltelacadscliente;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelCabCliente;
    private javax.swing.JPanel jPaneltlcliente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPanecadastrocliente;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldbairrocliente;
    private javax.swing.JTextField jTextFieldcidade;
    private javax.swing.JTextField jTextFieldcomplemento;
    private javax.swing.JTextField jTextFieldnomecliente;
    private javax.swing.JTextField jTextFieldnomeclienteIdentificador;
    private javax.swing.JTextField jTextFieldpesquisa;
    private javax.swing.JTextField jTextFieldruacliente;
    // End of variables declaration//GEN-END:variables
}
